# Generated by Django 5.2.7 on 2025-11-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('client', 'Клієнт')], default='client', max_length=10, verbose_name='Роль користувача'),
        ),
    ]
