# Generated by Django 5.2.7 on 2025-11-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Адмін'), ('manager', 'Менеджер'), ('client', 'Клієнт')], default='client', max_length=10, verbose_name='Роль користувача'),
        ),
    ]
