# Generated by Django 5.2.7 on 2025-11-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примітка'),
        ),
        migrations.AddField(
            model_name='credit',
            name='number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер кредиту'),
        ),
        migrations.AddField(
            model_name='credit',
            name='ostatok',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10, verbose_name='Залишок кредиту'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credit',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ціль кредиту'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='summa_credit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума кредиту'),
        ),
    ]
