# Generated by Django 5.2.7 on 2025-11-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0004_alter_customuser_ipn_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='IPN',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ІПН'),
        ),
    ]
