# Generated by Django 5.2.7 on 2025-11-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0004_credit_note_credit_number_credit_ostatok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Кредит закрит'),
        ),
    ]
