# Generated by Django 5.2.7 on 2025-11-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0005_credit_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='dolg_percent',
            field=models.DecimalField(decimal_places=2, default='2025-11-05', max_digits=5, verbose_name='Борг по оплаті %'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credit',
            name='last_pay_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата останнього платежу'),
        ),
    ]
