# Generated by Django 5.2.7 on 2025-11-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0005_credit_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='dolg_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Борг по оплаті %'),
        ),
        migrations.AddField(
            model_name='credit',
            name='last_pay_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата останнього платежу'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='day_of_pay',
            field=models.IntegerField(default=15, verbose_name='Плановий день оплати'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='percent',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Добова відсоткова ставка (%)'),
        ),
    ]
