# Generated by Django 5.2.7 on 2025-11-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0005_alter_customuser_ipn'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(blank=True, max_length=1, verbose_name='Стать'),
        ),
    ]
