# Generated by Django 5.2.7 on 2025-11-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0006_credit_dolg_percent_credit_last_pay_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='dolg_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Борг по оплаті %'),
        ),
        migrations.AddField(
            model_name='payment',
            name='ostatok',
            field=models.DecimalField(decimal_places=2, default=777, max_digits=10, verbose_name='Залишок кредиту'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='pog_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Погашено кредиту'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='pog_summa_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Погашено %'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='summa_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Нараховано %'),
            preserve_default=False,
        ),
    ]
