# Generated by Django 5.2.7 on 2025-11-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0006_customuser_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('m', 'Чоловіча'), ('w', 'Жіноча')], default='m', max_length=1, null=True, verbose_name='Стать'),
        ),
    ]
