# Generated by Django 5.2.7 on 2025-11-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0007_alter_customuser_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address_registration',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адреса проживання'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_residential',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адреса проживання'),
        ),
    ]
