# Generated by Django 5.2.7 on 2025-11-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0007_payment_dolg_percent_payment_ostatok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ost_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Залишок платежу'),
            preserve_default=False,
        ),
    ]
