# Generated by Django 5.2.7 on 2025-11-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0008_payment_ost_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='dolg_percent',
            field=models.FloatField(default=0, verbose_name='Борг по оплаті %'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='ostatok',
            field=models.FloatField(verbose_name='Залишок кредиту'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='percent',
            field=models.FloatField(verbose_name='Добова відсоткова ставка (%)'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='summa_credit',
            field=models.FloatField(verbose_name='Сума кредиту'),
        ),
    ]
