# Generated by Django 5.2.7 on 2025-11-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0008_customuser_address_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='passport_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата видачі паспорта'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='passport_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Номер паспорту'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='passport_series',
            field=models.CharField(blank=True, max_length=2, verbose_name='Серія паспорту'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='passport_vidan',
            field=models.CharField(blank=True, max_length=255, verbose_name='Орган що видав паспорт'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, verbose_name='Місце народження'),
        ),
    ]
