# Generated by Django 5.2.7 on 2025-11-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0009_customuser_passport_date_customuser_passport_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Нотатки'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Посада'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='work_place',
            field=models.CharField(blank=True, max_length=100, verbose_name='Місце роботи'),
        ),
    ]
