# Generated by Django 5.2.7 on 2025-11-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0010_customuser_notes_customuser_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address_registration',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адреса прописки'),
        ),
    ]
