# Generated by Django 5.2.7 on 2025-11-10 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0011_alter_customuser_address_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='IPN',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Введіть коректний ІПН — рівно 10 цифр.')], verbose_name='ІПН'),
        ),
    ]
