# Generated by Django 5.2.7 on 2025-11-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0012_alter_customuser_ipn'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='plan_pay',
            field=models.FloatField(blank=True, default=0, verbose_name='Плановий платіж'),
            preserve_default=False,
        ),
    ]
