# Generated by Django 5.2.7 on 2025-11-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0013_credit_plan_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='number1',
            field=models.CharField(blank=True, max_length=10, verbose_name='Номер1'),
        ),
        migrations.AddField(
            model_name='credit',
            name='number2',
            field=models.CharField(blank=True, max_length=4, verbose_name='Номер2'),
        ),
        migrations.AddField(
            model_name='credit',
            name='number3',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер3'),
        ),
    ]
