# Generated by Django 5.2.7 on 2025-11-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0014_credit_number1_credit_number2_credit_number3'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='credit',
            unique_together={('number1', 'number2')},
        ),
    ]
