# Generated by Django 5.2.7 on 2025-11-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0015_alter_credit_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='number1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядковий номер'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='number2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рік видачі'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='number3',
            field=models.CharField(blank=True, max_length=20, verbose_name='Постфікс/Підрозділ'),
        ),
    ]
