# Generated by Django 5.2.7 on 2025-11-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0016_alter_credit_number1_alter_credit_number2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['-number1', '-number2'], 'verbose_name': 'Кредит', 'verbose_name_plural': 'Кредити'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date_pay'], 'verbose_name': 'Платіж', 'verbose_name_plural': 'Платежі'},
        ),
        migrations.AlterField(
            model_name='credit',
            name='percent',
            field=models.FloatField(verbose_name='Відсоткова ставка (%)'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='srok_months',
            field=models.IntegerField(verbose_name='Термін (міс.)'),
        ),
    ]
