# Generated by Django 5.2.7 on 2025-11-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_system', '0017_alter_credit_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=300, verbose_name="Повне ім'я"),
        ),
    ]
